services:
  app:
    build: .
    image: sql-extractor:latest
    container_name: sql-extractor
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sarasvati;databaseName=MAXCELSASA;encrypt=false;trustServerCertificate=true;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=L4cl4v34dm1n
    # Si 'sarasvati' es la máquina local (Windows host), descomenta las líneas siguientes
    extra_hosts:
      - "sarasvati:192.168.6.51"
